name: Nix (Update nixpkgs)

on:
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update nixpkgs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update nixpkgs input
        run: nix flake update nixpkgs

      - name: Check flake
        run: nix flake check --no-build

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[gha] Nix: update nixpkgs"
          file_pattern: flake.lock
